name: CI Benchmark
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: install
        run: |
          sudo apt update 
          sudo apt install build-essential ninja-build cmake
      - name: fftw-download
        run: |
          wget https://www.fftw.org/fftw-3.3.10.tar.gz
          tar -xf fftw-3.3.10.tar.gz
      - name: configure-fftw
        working-directory: ./fftw-3.3.10
        run: |
          ./configure --enable-threads --enable-avx2 --enable-avx512
          make
          sudo make install
      - name: build
        run: |
          mkdir cmake-build-release
          cd cmake-build-release 
          cmake ../cpp -G Ninja -D CMAKE_BUILD_TYPE=Release -D ENABLE_CILK=OFF
          ninja
      - name: benchmark
        run: ./cmake-build-release/bench-naive --benchmark_format=json --benchmark_out=bench-naive.json

      # main for comparison
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          ref: main
      - name: build-main
        run: |
          mkdir cmake-build-release-main
          cd cmake-build-release-main 
          cmake -G Ninja -D CMAKE_BUILD_TYPE=Release ../cpp
          ninja
      - name: benchmark-main
        run: ./cmake-build-release-main/bench-naive --benchmark_format=json --benchmark_out=bench-naive-main.json

      - name: compare
        run: python3 cmake-build-release/_deps/google-benchmark-src/tools/compare.py bench-naive-main.json bench-naive.json
